In [1]:
import pandas as pd
import pandas as pd

In [2]:
df = pd.read_csv('google_play_store_dataset.csv')

In [3]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 10841 entries, 0 to 10840
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10841 non-null  str
 1   Category        10841 non-null  str
 2   Rating          9367 non-null   float64
 3   Reviews         10841 non-null  str
 4   Size            10841 non-null  str
 5   Installs        10841 non-null  str
 6   Type            10840 non-null  str
 7   Price           10841 non-null  str
 8   Content Rating  10840 non-null  str
 9   Genres          10841 non-null  str
 10  Last Updated    10841 non-null  str
 11  Current Ver     10833 non-null  str
 12  Android Ver     10838 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.1 MB

In [5]:
df.isnull().sum()

App                  0
Category             0
Rating            1474
Reviews              0
Size                 0
Installs             0
Type                 1
Price                0
Content Rating       1
Genres               0
Last Updated         0
Current Ver          8
Android Ver          3
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(483)

In [8]:
df.drop_duplicates(inplace = True)

In [9]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.1,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.9,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.7,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.5,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.3,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.5,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.0,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,NaN,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.5,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.5,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [10]:
df['Rating'] = df['Rating'].fillna(df['Rating'].mean(), inplace = True)

C:\Users\VIPUL KUMAR JAISWAL\AppData\Local\Temp\ipykernel_16044\3909316982.py:1: ChainedAssignmentError: A value is being set on a copy of a DataFrame or Series through chained assignment using an inplace method.
Such inplace method never works to update the original DataFrame or Series, because the intermediate object on which we are setting values always behaves as a copy (due to Copy-on-Write).

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' instead, to perform the operation inplace on the original object, or try to avoid an inplace operation using 'df[col] = df[col].method(value)'.

See the documentation for a more detailed explanation: https://pandas.pydata.org/pandas-docs/stable/user_guide/copy_on_write.html
  df['Rating'] = df['Rating'].fillna(df['Rating'].mean(), inplace = True)

In [11]:
df[df['Type'].isnull()].index

Index([9148], dtype='int64')

In [12]:
df['Type'] = df['Type'].fillna(df['Type'].mode()[0] )

In [13]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
0,Photo Editor & Candy Camera & Grid & ScrapBook,ART_AND_DESIGN,4.100000,159,19M,"10,000+",Free,0,Everyone,Art & Design,"January 7, 2018",1.0.0,4.0.3 and up
1,Coloring book moana,ART_AND_DESIGN,3.900000,967,14M,"500,000+",Free,0,Everyone,Art & Design;Pretend Play,"January 15, 2018",2.0.0,4.0.3 and up
2,"U Launcher Lite – FREE Live Cool Themes, Hide ...",ART_AND_DESIGN,4.700000,87510,8.7M,"5,000,000+",Free,0,Everyone,Art & Design,"August 1, 2018",1.2.4,4.0.3 and up
3,Sketch - Draw & Paint,ART_AND_DESIGN,4.500000,215644,25M,"50,000,000+",Free,0,Teen,Art & Design,"June 8, 2018",Varies with device,4.2 and up
4,Pixel Draw - Number Art Coloring Book,ART_AND_DESIGN,4.300000,967,2.8M,"100,000+",Free,0,Everyone,Art & Design;Creativity,"June 20, 2018",1.1,4.4 and up
...,...,...,...,...,...,...,...,...,...,...,...,...,...
10836,Sya9a Maroc - FR,FAMILY,4.500000,38,53M,"5,000+",Free,0,Everyone,Education,"July 25, 2017",1.48,4.1 and up
10837,Fr. Mike Schmitz Audio Teachings,FAMILY,5.000000,4,3.6M,100+,Free,0,Everyone,Education,"July 6, 2018",1.0,4.1 and up
10838,Parkinson Exercices FR,MEDICAL,4.189542,3,9.5M,"1,000+",Free,0,Everyone,Medical,"January 20, 2017",1.0,2.2 and up
10839,The SCP Foundation DB fr nn5n,BOOKS_AND_REFERENCE,4.500000,114,Varies with device,"1,000+",Free,0,Mature 17+,Books & Reference,"January 19, 2015",Varies with device,Varies with device
10840,iHoroscope - 2018 Daily Horoscope & Astrology,LIFESTYLE,4.500000,398307,19M,"10,000,000+",Free,0,Everyone,Lifestyle,"July 25, 2018",Varies with device,Varies with device

In [14]:
df.isnull().sum()

App               0
Category          0
Rating            0
Reviews           0
Size              0
Installs          0
Type              0
Price             0
Content Rating    1
Genres            0
Last Updated      0
Current Ver       8
Android Ver       3
dtype: int64

In [15]:
df['Content Rating'] = df['Content Rating'].fillna(df['Content Rating'].mode()[0])

In [16]:
df['Current Ver'] = df['Current Ver'].fillna('varies with device')

In [17]:
df['Android Ver'] = df['Android Ver'].fillna('varies with device')

In [18]:
df.sort_values(by = 'Installs' , ascending = False , inplace = True)

In [19]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,1.9,19.000000,3.0M,"1,000+",Free,0,Everyone,Everyone,"February 11, 2018",1.0.19,4.0 and up,varies with device
4115,Twitter,NEWS_AND_MAGAZINES,4.300000,11657972,Varies with device,"500,000,000+",Free,0,Mature 17+,News & Magazines,"July 30, 2018",Varies with device,Varies with device
347,imo free video calls and chat,COMMUNICATION,4.300000,4785892,11M,"500,000,000+",Free,0,Everyone,Communication,"June 8, 2018",9.8.000000010501,4.0 and up
3265,Gboard - the Google Keyboard,TOOLS,4.200000,1859115,Varies with device,"500,000,000+",Free,0,Everyone,Tools,"July 31, 2018",Varies with device,Varies with device
4005,Clean Master- Space Cleaner & Antivirus,TOOLS,4.700000,42916526,Varies with device,"500,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9719,EP Cook Book,MEDICAL,4.189542,0,3.2M,0+,Paid,$200.00,Everyone,Medical,"July 26, 2015",1.0,3.0 and up
5945,Ain Arabic Kids Alif Ba ta,FAMILY,4.189542,0,33M,0+,Paid,$2.99,Everyone,Education,"April 15, 2016",1.0,3.0 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.189542,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
5307,Ak Parti Yardım Toplama,SOCIAL,4.189542,0,8.7M,0+,Paid,$13.99,Teen,Social,"July 28, 2017",3.4.4.3.3,4.1 and up
9148,Command & Conquer: Rivals,FAMILY,4.189542,0,Varies with device,0,Free,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [20]:
df['Reviews'].unique()

<StringArray>
[    '3.0M', '11657972',  '4785892',  '1859115', '42916526', '22428456',
 '11334799', '10485334', '17014787',  '1284017',
 ...
    '26545',    '40467',     '5511',    '40035',     '8780',    '59632',
    '24565',     '7342',      '594',      '200']
Length: 6002, dtype: str

In [21]:
df.loc[10472 , 'Category'] = "photo_frame"

In [22]:
df.loc[10472 , 'Rating'] = 1.9

In [23]:
df.loc[10472 , 'Reviews'] = "can't predict"

In [24]:
df.loc[10472 , 'Size'] = '3.0M'

In [25]:
df.loc[10472 , 'Installs'] = df['Installs'].mode()[0]

In [26]:
df.loc[10472 , 'Type'] = 'Free'

In [27]:
df.loc[10472 , 'Price'] = df['Price'].mode()[0]

In [28]:
df.loc[10472 , 'Genres'] = 'Tool'

In [29]:
df

,App,Category,Rating,Reviews,Size,Installs,Type,Price,Content Rating,Genres,Last Updated,Current Ver,Android Ver
10472,Life Made WI-Fi Touchscreen Photo Frame,photo_frame,1.900000,can't predict,3.0M,"1,000,000+",Free,0,Everyone,Tool,1.0.19,4.0 and up,varies with device
4115,Twitter,NEWS_AND_MAGAZINES,4.300000,11657972,Varies with device,"500,000,000+",Free,0,Mature 17+,News & Magazines,"July 30, 2018",Varies with device,Varies with device
347,imo free video calls and chat,COMMUNICATION,4.300000,4785892,11M,"500,000,000+",Free,0,Everyone,Communication,"June 8, 2018",9.8.000000010501,4.0 and up
3265,Gboard - the Google Keyboard,TOOLS,4.200000,1859115,Varies with device,"500,000,000+",Free,0,Everyone,Tools,"July 31, 2018",Varies with device,Varies with device
4005,Clean Master- Space Cleaner & Antivirus,TOOLS,4.700000,42916526,Varies with device,"500,000,000+",Free,0,Everyone,Tools,"August 3, 2018",Varies with device,Varies with device
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9719,EP Cook Book,MEDICAL,4.189542,0,3.2M,0+,Paid,$200.00,Everyone,Medical,"July 26, 2015",1.0,3.0 and up
5945,Ain Arabic Kids Alif Ba ta,FAMILY,4.189542,0,33M,0+,Paid,$2.99,Everyone,Education,"April 15, 2016",1.0,3.0 and up
8871,Test Application DT 02,ART_AND_DESIGN,4.189542,0,1.2M,0+,Free,0,Everyone,Art & Design,"March 14, 2017",4.0,4.2 and up
5307,Ak Parti Yardım Toplama,SOCIAL,4.189542,0,8.7M,0+,Paid,$13.99,Teen,Social,"July 28, 2017",3.4.4.3.3,4.1 and up
9148,Command & Conquer: Rivals,FAMILY,4.189542,0,Varies with device,0,Free,0,Everyone 10+,Strategy,"June 28, 2018",Varies with device,Varies with device

In [30]:
df.info()

<class 'pandas.DataFrame'>
Index: 10358 entries, 10472 to 9148
Data columns (total 13 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   App             10358 non-null  str
 1   Category        10358 non-null  str
 2   Rating          10358 non-null  float64
 3   Reviews         10358 non-null  str
 4   Size            10358 non-null  str
 5   Installs        10358 non-null  str
 6   Type            10358 non-null  str
 7   Price           10358 non-null  str
 8   Content Rating  10358 non-null  str
 9   Genres          10358 non-null  str
 10  Last Updated    10358 non-null  str
 11  Current Ver     10358 non-null  str
 12  Android Ver     10358 non-null  str
dtypes: float64(1), str(12)
memory usage: 1.4 MB

In [31]:
df.to_csv('Cleaned_google_playstore_dataset.csv')